version: "3.7"
services:
    app:
        build:
            context: ./
            dockerfile: Dockerfile
            args:
                user: agung
                uid: 1000
        image: auth-services:1.0
        container_name: pec-auth-services
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        environment:
            DB_HOST: mysql_container
            DB_PORT: 3306
            DB_DATABASE: pec_authservice
            DB_USERNAME: root
            DB_PASSWORD: rootpassword
        networks:
            - auth-services
            - db-network # network terhubung ke mysql

    nginx:
        image: nginx:alpine
        container_name: web-server-auth-services
        restart: unless-stopped
        ports:
            - "8081:80"
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d/
        networks:
            - auth-services
            - db-network

networks:
    auth-services:
        driver: bridge
    db-network:
        external: true
