version: "3.7"
services:
    app:
        build:
            context: ./
            dockerfile: Dockerfile
            args:
                user: agung
                uid: 1000
        image: pec-auth-services:1.0
        container_name: pec-auth-services
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        environment:
            DB_HOST: mysql_container # Nama kontainer MySQL
            DB_PORT: 3306 # Port MySQL dalam kontainer
            DB_DATABASE: pec_authservice # Nama database
            DB_USERNAME: root # Username
            DB_PASSWORD: rootpassword # Password
        networks:
            - pec-authservice-network
            - mynetwork # network terhubung ke mysql

    nginx:
        image: nginx:alpine
        container_name: web-server-nginx
        restart: unless-stopped
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d/
        networks:
            - pec-authservice-network

networks:
    pec-authservice-network:
        driver: bridge
    mynetwork:
        external: true
